version: '3'
services:
  internalcrm:
    container_name: internalcrm
    build:
      context: InternalCRM
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    expose:
      - 9090
  virtualcrm:
    container_name: virtualcrm
    build:
      context: VirtualCRM
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
